### ISSUE TITLE
no target specified first build

### ISSUE THREAD

**Issue by SeleDreams** [flipacholas/Docker-PS3DevExtra#3]
![image](https://user-images.githubusercontent.com/16335601/60516431-07db5c00-9cde-11e9-808c-fe0bb08aa10a.png)

I tried installing the docker image but i have an error at the first line because it can't find a makefile

**Comment by flipacholas** [comment]
I know this sounds silly but is there a makefile in your project's folder?

**Comment by SeleDreams** [comment]
*facepalm* I just noticed that i didn't run it from my project's directory


sorry for wasting your time lol

**Comment by flipacholas** [comment]
that's fine mate
